<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
//phpcs:disable Squiz.ControlStructures.ControlSignature.NewlineAfterOpenBrace
//phpcs:disable Squiz.WhiteSpace.ScopeClosingBrace.ContentBefore
//phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
//phpcs:disable Magento2.Files.LineLength.MaxExceeded
?>
<?php
/**
 * @var $block \Magento\Shipping\Block\Items
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\OrderShippingAdditionalInfo
 */
?>
<?php
$_order = $block->getOrder();
$viewModel = $block->getViewModel();
$viewModel->setOrder($_order);
?>
<div class="actions-toolbar">
    <?php if ($_order->getTracksCollection()->count()) : ?>
        <?= $block->getChildHtml('track-all-link') ?>
    <?php endif; ?>
    <a href="<?= $block->escapeUrl($block->getPrintAllShipmentsUrl($_order)) ?>"
       class="action print"
       target="_blank"
       rel="noopener">
        <span><?= $block->escapeHtml(__('Print All Shipments')) ?></span>
    </a>
</div>
<?php foreach ($_order->getShipmentsCollection() as $_shipment) : ?>
    <div class="order-title">
        <strong><?= $block->escapeHtml(__('Shipment #')) ?><?= $block->escapeHtml($_shipment->getIncrementId()) ?></strong>
        <a href="<?= $block->escapeUrl($block->getPrintShipmentUrl($_shipment)) ?>"
           class="action print"
           target="_blank"
           rel="noopener">
            <span><?= $block->escapeHtml(__('Print Shipment')) ?></span>
        </a>
        <?php if ($viewModel->isTrackable($_shipment)): ?>
        <a href="#"
           data-mage-init='{"popupWindow": {"windowURL":"<?= $block->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($_shipment)) ?>","windowName":"trackshipment","width":800,"height":600,"top":0,"left":0,"resizable":1,"scrollbars":1}}'
           title="<?= $block->escapeHtml(__('Track this shipment')) ?>"
           class="action track">
            <span><?= $block->escapeHtml(__('Track this shipment')) ?></span>
        </a>
        <?php endif; ?>
    </div>
    <?php $tracks = $_shipment->getTracksCollection(); ?>
    <?php  if ($tracks->count()) : ?>
        <dl class="order-tracking" id="my-tracking-table-<?= (int) $_shipment->getId() ?>">
            <dt class="tracking-title">
                <?= $block->escapeHtml(__('Tracking Number(s):')) ?>
            </dt>
            <dd class="tracking-content">
                <?php
                $i = 1;
                $_size = $tracks->count();
                foreach ($tracks as $track) : ?>
                    <?php if ($track->isCustom()) : ?>
                        <?= $block->escapeHtml($track->getNumber()) ?>
                    <?php else : ?>
                        <?php if ($viewModel->isTrackable($_shipment)): ?>
                            <a href="#"
                                data-mage-init='{"popupWindow": {"windowURL":"<?= $block->escapeUrl($this->helper(Magento\Shipping\Helper\Data::class)->getTrackingPopupUrlBySalesModel($track)) ?>","windowName":"trackorder","width":800,"height":600,"left":0,"top":0,"resizable":1,"scrollbars":1}}'
                                class="action track"><span><?= $block->escapeHtml($track->getNumber()) ?></span>
                                </a>
                        <?php else: ?>
                            <span class="track"><?= $block->escapeHtml($track->getNumber()) ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php if ($i != $_size) : ?>, <?php endif; ?>
                    <?php $i++;
                endforeach; ?>
            </dd>
        </dl>
    <?php  endif; ?>
    <div class="table-wrapper order-items-shipment">
        <table class="data table table-order-items shipment" id="my-shipment-table-<?= (int) $_shipment->getId() ?>">
            <caption class="table-caption"><?= $block->escapeHtml(__('Items Shipped')) ?></caption>
            <thead>
                <tr>
                    <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                    <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                    <th class="col qty"><?= $block->escapeHtml(__('Qty Shipped')) ?></th>
                </tr>
            </thead>
            <?php $_items = $_shipment->getAllItems(); ?>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                    <tbody>
                        <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
    </div>
    <?= $block->getCommentsHtml($_shipment) ?>
<?php endforeach; ?>
