image: alpine:3.21

before_script:
    - apk add openssh-client

stages:
    - deploy

deploy_staging:
    tags:
        - calcurates
    stage: deploy
    script:
        - echo "Deploy to staging server"
        - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d | tr -d '\r' > ./id_rsa
        - chmod 600 ./id_rsa
        - ssh -o StrictHostKeyChecking=no -p"$SSH_PORT" -i ./id_rsa "$SSH_USER"@"$SSH_STAGING_HOST" "$SSH_STAGING_DEPLOY_SCRIPT"
    only:
        - dev

deploy_demo:
    tags:
        - calcurates
    stage: deploy
    script:
        - echo "Deploy to demo server"
        - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d | tr -d '\r' > ./id_rsa
        - chmod 600 ./id_rsa
        - ssh -o StrictHostKeyChecking=no -p"$SSH_PORT" -i ./id_rsa "$SSH_USER"@"$SSH_DEMO_HOST" "$SSH_DEMO_DEPLOY_SCRIPT"
    when: manual
    only:
        - master
