image: alpine:3.24

before_script:
    - apk add openssh-client

stages:
    - lint
    - deploy

lint:
    image: php:8.5-cli-alpine
    tags:
        - calcurates
    stage: lint
    allow_failure: true
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    before_script:
        - apk add --no-cache curl
    script:
        - echo "Run php-cs-fixer (latest v3, dry-run, @PSR12)"
        - curl -fsSL https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer.phar
        - php php-cs-fixer.phar fix . --rules=@PSR12 --dry-run --diff --using-cache=no --no-interaction

deploy_staging:
    tags:
        - calcurates
    stage: deploy
    script:
        - echo "Deploy to staging server"
        - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d | tr -d '\r' > ./id_rsa
        - chmod 600 ./id_rsa
        - ssh -o StrictHostKeyChecking=no -p"$SSH_PORT" -i ./id_rsa "$SSH_USER"@"$SSH_STAGING_HOST" "$SSH_STAGING_DEPLOY_SCRIPT"
    only:
        - dev

deploy_demo:
    tags:
        - calcurates
    stage: deploy
    script:
        - echo "Deploy to demo server"
        - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d | tr -d '\r' > ./id_rsa
        - chmod 600 ./id_rsa
        - ssh -o StrictHostKeyChecking=no -p"$SSH_PORT" -i ./id_rsa "$SSH_USER"@"$SSH_DEMO_HOST" "$SSH_DEMO_DEPLOY_SCRIPT"
    when: manual
    only:
        - master
