<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
/** @var $block \Calcurates\ModuleMagento\Block\Adminhtml\Order\View\DeliveryDate */
/** @var $viewModel \Calcurates\ModuleMagento\ViewModel\OrderDeliveryDate */
/** @var \Magento\Framework\Escaper $escaper */
$viewModel = $block->getViewModel();

$orderData = $viewModel->getOrderDataByOrderId((int)$block->getOrder()->getId());
$hasDeliveryDateAndTime = $orderData && $orderData->getDeliveryDate();
$deliveryDatesFormatted = '';
if ($orderData) {
    $deliveryDatesFormatted = $viewModel->formatDeliveryDates($orderData->getDeliveryDates());
}
?>

<?php if ($deliveryDatesFormatted || $hasDeliveryDateAndTime): ?>
    <section class="admin__page-section order-view-billing-shipping">
        <div class="admin__page-section-title">
            <span class="title"><?= $block->escapeHtml(__('Delivery Dates')) ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-information">
                <div class="admin__page-section-item-content">

                    <table class="admin__table-secondary order-information-table">
                        <tbody>
                        <?php if ($deliveryDatesFormatted && !$hasDeliveryDateAndTime): ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Estimated Delivery Dates')) ?></th>
                                <td><?= $block->escapeHtml($deliveryDatesFormatted) ?></td>
                            </tr>
                        <?php endif; ?>

                        <?php if ($hasDeliveryDateAndTime): ?>
                            <tr>
                                <th><?= $block->escapeHtml(__('Selected Delivery Date')) ?></th>
                                <td>
                                    <?= /** @noEscape  */ $viewModel->formatDate($orderData->getDeliveryDate()) ?>
                                </td>
                            </tr>

                            <?php if ($orderData->getDeliveryDateTimeFrom() || $orderData->getDeliveryDateTimeTo()): ?>
                                <tr>
                                    <th><?= $block->escapeHtml(__('Selected Delivery Time')) ?></th>
                                    <td>
                                        <?= /** @noEscape  */ $viewModel->formatTimeInterval(
                                            $orderData->getDeliveryDateTimeFrom(),
                                            $orderData->getDeliveryDateTimeTo()
                                        ) ?>
                                    </td>
                                </tr>
                            <?php endif; ?>
                        <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
<?php endif; ?>
