<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\AbstractOrder
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\OrderSplitShipments
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var $escaper \Magento\Framework\Escaper
 */

/** @var \Magento\Shipping\Helper\Data $shippingHelper */
$shippingHelper = $block->getData('shippingHelper');
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
$viewModel = $block->getViewModel();
$viewModel->setOrder($block->getOrder());
?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()):
    return '';
endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= $escaper->escapeHtml(__('Shipping &amp; Handling Information')) ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()): ?>
            <p>
                <a href="#" id="linkId" title="<?= $escaper->escapeHtmlAttr(__('Track Order')) ?>">
                    <?= $escaper->escapeHtml(__('Track Order')) ?>
                </a>
            </p>
            <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                'onclick',
                "popWin('" . $block->escapeJs($shippingHelper->getTrackingPopupUrlBySalesModel($order)) .
                "','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')",
                'a#linkId'
            ) ?>
        <?php endif; ?>
        <?php if($viewModel->isSplitShipment()) : ?>
            <?php $shipmentCount = count($viewModel->getOrderData()->getSplitShipments()) ?>
            <?php foreach ($viewModel->getOrderData()->getSplitShipments() as $key => $splitShipment): ?>
                <b><?= $escaper->escapeHtml(__('Shipment %1 of %2:', $key + 1, $shipmentCount)) ?></b><br>
                <span><?= $escaper->escapeHtml($splitShipment['title'] ?? '')?></span>&nbsp;-&nbsp;
                <b><?= $escaper->escapeHtml($viewModel->getMethodPrice($splitShipment['price'] ?? 0)) ?></b>
                <br>
                <span>
                    <?= $escaper->escapeHtml(__('Included SKUs: %1', implode(', ', $splitShipment['products'] ?? []))) ?>
                </span><br>
            <?php endforeach; ?>
        <?php else : ?>
            <?php if ($order->getShippingDescription()): ?>
                <strong><?= $escaper->escapeHtml($order->getShippingDescription()) ?></strong>

                <?php if ($taxHelper->displayShippingPriceIncludingTax()): ?>
                    <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
                <?php else: ?>
                    <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                <?php endif; ?>
                <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

                <?= /** @noEscape */ $_excl ?>
                <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?= $escaper->escapeHtml(__('Incl. Tax')) ?> <?= /** @noEscape */ $_incl ?>)
                <?php endif; ?>
            <?php else: ?>
                <?= $escaper->escapeHtml(__('No shipping information available')) ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
