<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\AbstractOrder
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\OrderShippingAdditionalInfo
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 * @var $escaper \Magento\Framework\Escaper
 */

$viewModel = $block->getViewModel();
$viewModel->setOrder($block->getOrder());
/** @var \Magento\Shipping\Helper\Data $shippingHelper */
$shippingHelper = $block->getData('shippingHelper') ?? $viewModel->getShippingHelper();
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper') ?? $viewModel->getTaxHelper();
?>
<?php $order = $block->getOrder() ?>
<?php if ($order->getIsVirtual()):
    return '';
endif; ?>

<?php /* Shipping Method */ ?>
<div class="admin__page-section-item order-shipping-method">
    <div class="admin__page-section-item-title">
        <span class="title"><?= $block->escapeHtml(__('Shipping &amp; Handling Information')) ?></span>
    </div>
    <div class="admin__page-section-item-content">
        <?php  if ($order->getTracksCollection()->count()): ?>
            <?php if (isset($secureRenderer)): ?>
                <p>
                    <a href="#" id="linkId" title="<?= $block->escapeHtmlAttr(__('Track Order')) ?>">
                        <?= $block->escapeHtml(__('Track Order')) ?>
                    </a>
                </p>
                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                    'onclick',
                    "popWin('" . $block->escapeJs($shippingHelper->getTrackingPopupUrlBySalesModel($order)) .
                    "','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')",
                    'a#linkId'
                ) ?>
            <?php else: ?>
                <p><a href="#" id="linkId" onclick="popWin('<?= $block->escapeHtmlAttr($block->escapeJs(
                    $block->escapeUrl($shippingHelper->getTrackingPopupUrlBySalesModel($order))
                )) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"
                      title="<?= $block->escapeHtmlAttr(__('Track Order')) ?>">
                    <?= $block->escapeHtml(__('Track Order')) ?>
                </a></p>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($viewModel->isSplitShipment()): ?>
            <?php $shipmentCount = count($viewModel->getOrderData()->getSplitShipments()) ?>
            <?php foreach ($viewModel->getOrderData()->getSplitShipments() as $key => $splitShipment): ?>
                <b><?= $block->escapeHtml(__('Shipment %1 of %2:', $key + 1, $shipmentCount)) ?></b><br>
                <span><?= $block->escapeHtml($splitShipment['title'] ?? '')?></span>&nbsp;-&nbsp;
                <b><?= $block->escapeHtml($viewModel->getMethodPrice($splitShipment['price'] ?? 0)) ?></b>
                <br>
                <span>
                    <?= $block->escapeHtml(__('Included SKUs: %1', implode(', ', $splitShipment['products'] ?? []))) ?>
                </span><br>
            <?php endforeach; ?>
            <?php if (count($viewModel->getPackages())): ?>
                <div class="shipping-packages-title"><b><?= $block->escapeHtml(__('Packages'))?>:</b></div>
                <?php foreach ($viewModel->getPackagesQty() as $title => $count): ?>
                    <span><?= $block->escapeHtml(__('%1 x %2', $count, $title)) ?></span><br>
                <?php endforeach; ?>
            <?php endif; ?>
        <?php else: ?>
            <?php if ($order->getShippingDescription()): ?>
                <strong><?= $block->escapeHtml($order->getShippingDescription()) ?></strong>

                <?php if ($taxHelper->displayShippingPriceIncludingTax()): ?>
                    <?php $_excl = $block->displayShippingPriceInclTax($order); ?>
                <?php else: ?>
                    <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                <?php endif; ?>
                <?php $_incl = $block->displayShippingPriceInclTax($order); ?>

                <?= /** @noEscape */ $_excl ?>
                <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                    (<?= $block->escapeHtml(__('Incl. Tax')) ?> <?= /** @noEscape */ $_incl ?>)
                <?php endif; ?>
                <?php if (count($viewModel->getPackages())): ?>
                    <div class="shipping-packages-title"><b><?= $block->escapeHtml(__('Packages'))?>:</b></div>
                    <?php foreach ($viewModel->getPackagesQty() as $title => $count): ?>
                        <span><?= $block->escapeHtml(__('%1 x %2', $count, $title)) ?></span><br>
                    <?php endforeach; ?>
                <?php endif; ?>
            <?php else: ?>
                <?= $block->escapeHtml(__('No shipping information available')) ?>
            <?php endif; ?>
        <?php endif; ?>
    </div>
</div>
