<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2019-2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
?>
<?php /** @var $block \Calcurates\ModuleMagento\Block\Adminhtml\Shipping\Create */?>

<script>
    require([
        "jquery"
    ], function(jQuery){
        var checkboxLabel = jQuery('label[for=create_shipping_label] span'),
            text = "<?= $block->escapeHtml(__('Create Shipping Label with Calcurates')) ?>",
            isNeedReplace = <?= $block->isNeedReplaceCheckboxLabel() ? 'true' : 'false' ?>;

        if (isNeedReplace && checkboxLabel.length > 0) {
            checkboxLabel.text(text);
        }
    });
</script>
