<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2019-2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
?>
<?php /** @var $block \Calcurates\ModuleMagento\Block\Adminhtml\Shipping\LabelDataRenderer */?>
<?php /** @var $escaper \Magento\Framework\Escaper */?>
<?php
$items = $block->getLabelData();
if (!$items) {
    return;
}
$printUrl = $block->getUrl('adminhtml/order_shipment/printCalcuratesLabel', [
    'shipment_id' => $block->getShippingLabel()->getShipmentId(),
    'shipping_label_id' => $block->getShippingLabel()->getId()
]);

$downloadLinkLabel = isset($block->getShippingLabel()->getLabelData()['formDownload'])
    ? __('Download label and custom form')
    : __('Download label');
?>

<div class="admin__page-section-item-title">
    <span class="title"><?= $block->escapeHtml(__('Label Info')) ?></span>
</div>
<table class="admin__table-secondary">
    <tbody>
    <?php foreach ($items as $item): ?>
        <tr>
            <th><?= $block->escapeHtml($item['label']) ?></th>
            <td><?= $block->escapeHtml($item['value']) ?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <th></th>
        <td><a href="<?= $block->escapeUrl($printUrl) ?>"><?= $block->escapeHtml($downloadLinkLabel) ?></a></td>
    </tr>
    </tbody>
</table>
