<?php /** @var $block \Calcurates\ModuleMagento\Block\Adminhtml\Shipping\LabelDataRenderer */?>
<?php
$items = $block->getLabelData();
if (!$items) {
    return;
}
?>

<div class="admin__page-section-item-title">
    <span class="title"><?= __('Label Info') ?></span>
</div>
<table class="admin__table-secondary">
    <tbody>
    <?php foreach ($items as $item): ?>
        <tr>
            <th><?= $item['label']?></th>
            <td><?= $item['value']?></td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <th></th>
        <td><a href="<?= $block->getPrintUrl() ?>"><?= __('Download label') ?></a></td>
    </tr>
    </tbody>
</table>
