<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var $block Magento\Shipping\Block\Adminhtml\Order\Tracking\View
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\OrderShippingAdditionalInfo
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Sales\Model\Order $order */
$order = $block->getShipment()->getOrder();
$viewModel = $block->getViewModel();
$viewModel->setOrder($order);
/** @var \Magento\Shipping\Helper\Data $shippingHelper */
$shippingHelper = $block->getData('shippingHelper') ?? $viewModel->getShippingHelper();

?>
<div class="admin__control-table-wrapper">
    <form id="tracking-shipping-form" data-mage-init='{"validation": {}}'>
        <table class="data-table admin__control-table" id="shipment_tracking_info">
            <thead>
                <tr class="headings">
                    <th class="col-carrier"><?= $block->escapeHtml(__('Carrier')) ?></th>
                    <th class="col-title"><?= $block->escapeHtml(__('Title')) ?></th>
                    <th class="col-number"><?= $block->escapeHtml(__('Number')) ?></th>
                    <th class="col-delete last"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <td class="col-carrier">
                        <select name="carrier"
                                class="select admin__control-select"
                                onchange="selectCarrier(this)">
                            <?php foreach ($block->getCarriers() as $_code => $_name): ?>
                            <option value="<?= $block->escapeHtmlAttr($_code) ?>">
                                <?= $block->escapeHtml($_name) ?></option>
                            <?php endforeach; ?>
                        </select>
                    </td>
                    <td class="col-title">
                        <input class="input-text admin__control-text"
                               type="text"
                               id="tracking_title"
                               name="title"
                               value="" />
                    </td>
                    <td class="col-number">
                        <input class="input-text admin__control-text required-entry"
                               type="text"
                               id="tracking_number"
                               name="number"
                               value="" />
                    </td>
                    <td class="col-delete last"><?= $block->getSaveButtonHtml() ?></td>
                </tr>
            </tfoot>
        <?php if ($_tracks = $block->getShipment()->getAllTracks()): ?>
            <tbody>
            <?php $i = 0;
            foreach ($_tracks as $_track): $i++ ?>
                <tr class="<?= /* @noEscape */ ($i % 2 == 0) ? 'even' : 'odd' ?>">
                    <td class="col-carrier">
                        <?= $block->escapeHtml($block->getCarrierTitle($_track->getCarrierCode())) ?>
                    </td>
                    <td class="col-title"><?= $block->escapeHtml($_track->getTitle()) ?></td>
                    <td class="col-number">
                        <?php if ($_track->isCustom()): ?>
                            <?= $block->escapeHtml($_track->getNumber()) ?>
                        <?php else: ?>
                            <?php if ($viewModel->isTrackable()): ?>
                                <?php if (isset($secureRenderer)): ?>
                                    <a id="col-track-<?= (int) $_track->getId() ?>" href="#">
                                    <?= $block->escapeHtml($_track->getNumber()) ?>
                                     </a>
                                    <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                                        'onclick',
                                        "event.preventDefault();
                                        popWin('{$block->escapeJs($shippingHelper->getTrackingPopupUrlBySalesModel($_track))}',
                                        'trackorder','width=800,height=600,resizable=yes,scrollbars=yes')",
                                        'a#col-track-' .  (int) $_track->getId()
                                    ) ?>
                                <?php else: ?>
                                    <a href="#" onclick="popWin('<?= $block->escapeHtmlAttr($block->escapeJs($block->escapeUrl($shippingHelper->getTrackingPopupUrlBySalesModel($_track)))) ?>','trackorder','width=800,height=600,resizable=yes,scrollbars=yes')"><?= $block->escapeHtml($_track->getNumber()) ?></a>
                                <?php endif; ?>
                                <div id="shipment_tracking_info_response_<?= (int) $_track->getId() ?>"></div>
                            <?php else: ?>
                                <span id="col-track-<?= (int) $_track->getId() ?>">
                                    <?= $block->escapeHtml($_track->getNumber()) ?>
                                </span>
                            <?php endif; ?>
                        <?php endif; ?>
                    </td>
                    <?php if (isset($secureRenderer)): ?>
                        <td class="col-delete last">
                            <button class="action-delete" type="button" id="del-track-<?= (int) $_track->getId() ?>">
                                <span><?= $block->escapeHtml(__('Delete')) ?></span>
                            </button>
                        </td>
                        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                            'onclick',
                            "deleteTrackingNumber('{$block->escapeJs($block->getRemoveUrl($_track))}');
                             event.preventDefault();",
                            '#del-track-' . (int) $_track->getId()
                        ) ?>
                    <?php else: ?>
                        <td class="col-delete last"><button class="action-delete" type="button" onclick="deleteTrackingNumber('<?= $block->escapeJs($block->escapeUrl($block->getRemoveUrl($_track))) ?>'); return false;"><span><?= $block->escapeHtml(__('Delete')) ?></span></button></td>
                    <?php endif; ?>
                </tr>
            <?php endforeach; ?>
            </tbody>
        <?php endif; ?>
        </table>
    </form>
</div>
<?php $scriptString = <<<script

require(['prototype', 'jquery', 'Magento_Ui/js/modal/confirm'], function(prototype, \$j, confirm) {
//<![CDATA[
function selectCarrier(elem) {
    var option = elem.options[elem.selectedIndex];
    $('tracking_title').value = option.value && option.value != 'custom' ? option.text : '';
}

function saveTrackingInfo(node, url) {
    var form = \$j('#tracking-shipping-form');

    if (form.validation() && form.validation('isValid')) {
        submitAndReloadArea(node, url);
    }
}

function deleteTrackingNumber(url) {
    confirm({
        content: '{$block->escapeJs(__('Are you sure?'))}',
        actions: {
            /**
             * Confirm action.
             */
            confirm: function () {
                submitAndReloadArea($('shipment_tracking_info').parentNode, url);
            }
        }
    });
}

window.selectCarrier = selectCarrier;
window.deleteTrackingNumber = deleteTrackingNumber;
window.saveTrackingInfo = saveTrackingInfo;
//]]>

});

script;
?>
<?php if (isset($secureRenderer)): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else: ?>
    <script>
        <?= /** @noEscape  */ $scriptString ?>
    </script>
<?php endif; ?>
