<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2021 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
/**
 * @var $block \Calcurates\ModuleMagento\Block\Order\DeliveryDateTime
 * @var $deliveryDateModel \Calcurates\ModuleMagento\ViewModel\OrderDeliveryDate
 * @var $escaper \Magento\Framework\Escaper
 */
$deliveryDateModel = $block->getOrderDeliveryDate();

$orderId = $block->getOrder() ? $block->getOrder()->getId() : $block->getOrderId();
$orderData = $deliveryDateModel->getOrderDataByOrderId((int)$orderId);
$hasDeliveryDateAndTime = $orderData && $orderData->getDeliveryDate();
$deliveryDatesFormatted = $orderData ? $deliveryDateModel->formatDeliveryDates($orderData->getDeliveryDates()) : '';
$type = $block->getType();
?>
<?php if ($deliveryDatesFormatted && !$hasDeliveryDateAndTime && $type === 'date'): ?>
    <?= /* @noEscape */ $deliveryDatesFormatted ?>
<?php endif; ?>
<?php if ($hasDeliveryDateAndTime): ?>
    <?php if ($type == 'date'): ?>
        <?= /* @noEscape */ $deliveryDateModel->formatDate($orderData->getDeliveryDate()) ?>
        <?= $block->escapeHtml($orderData->getDeliveryDateLabel()); ?>
    <?php elseif ($type == 'time' && ($orderData->getDeliveryDateTimeFrom() || $orderData->getDeliveryDateTimeTo())): ?>
        <?= /* @noEscape */ $deliveryDateModel->formatTimeInterval(
            $orderData->getDeliveryDateTimeFrom(),
            $orderData->getDeliveryDateTimeTo()
        ) ?>
        <?= $block->escapeHtml($orderData->getDeliveryDateTimeLabel()); ?>
    <?php endif; ?>
<?php endif; ?>
