<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
?>
<?php
/**
 * @var $block \Magento\Shipping\Block\Tracking\Link
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\OrderShippingAdditionalInfo
 */
?>
<?php
$order = $block->getOrder();
$viewModel = $block->getViewModel();
$viewModel->setOrder($order);
?>
<?php if ($viewModel->isTrackable()): ?>
<a href="#" class="action track" title="<?= $block->escapeHtmlAttr($block->getLabel()) ?>"
   data-mage-init='{"popupWindow": {
        "windowURL":"<?= $block->escapeUrl($block->getWindowUrl($order)) ?>",
        "windowName":"trackorder",
        "width":800,
        "height":600,
        "left":0,
        "top":0,
        "resizable":1,
        "scrollbars":1
    }}'>
    <span><?= $block->escapeHtml($block->getLabel()) ?></span>
</a>
<?php endif; ?>
