<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var $block \Magento\Sales\Block\Order\Email\Invoice\Items
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\OrderShippingAdditionalInfo
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php $_invoice = $block->getInvoice() ?>
<?php $_order   = $block->getOrder() ?>
<?php if ($_invoice && $_order): ?>
    <?php $viewModel = $block->getViewModel() ?>
    <?php $viewModel->setOrder($_order) ?>
    <?php if ($viewModel->isSplitShipment()): ?>
        <table class="order-details">
            <tbody>
            <tr>
                <td><h3><?= $block->escapeHtml(__('Split Shipments')) ?></h3></td>
            </tr>
            <?php $shipmentCount = count($viewModel->getOrderData()->getSplitShipments()) ?>
            <?php foreach ($viewModel->getOrderData()->getSplitShipments() as $key => $splitShipment): ?>
                <tr>
                    <td>
                        <b><?= $block->escapeHtml(__('Shipment %1 of %2:', $key + 1, $shipmentCount)) ?></b><br>
                        <span><?= $block->escapeHtml($splitShipment['title'] ?? '')?></span><br>
                        <span>
                        <?= $block->escapeHtml(
                            __('Included SKUs: %1', implode(', ', $viewModel->getProductList($splitShipment) ?? []))
                        ) ?>
                    </span><br>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    <?php endif; ?>
    <table class="email-items">
        <thead>
            <tr>
                <th class="item-info">
                    <?= $block->escapeHtml(__('Items')) ?>
                </th>
                <th class="item-qty">
                    <?= $block->escapeHtml(__('Qty')) ?>
                </th>
                <th class="item-subtotal">
                    <?= $block->escapeHtml(__('Subtotal')) ?>
                </th>
            </tr>
        </thead>
        <?php foreach ($_invoice->getAllItems() as $_item): ?>
            <?php if (!$_item->getOrderItem()->getParentItem()): ?>
                <tbody>
                    <?= $block->getItemHtml($_item) ?>
                </tbody>
            <?php endif; ?>
        <?php endforeach; ?>
        <tfoot class="order-totals">
            <?= $block->getChildHtml('invoice_totals') ?>
        </tfoot>
    </table>
<?php endif; ?>
