<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2019-2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var \Magento\Shipping\Block\Adminhtml\Order\Packaging\Grid $block
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Calcurates\ModuleMagento\ViewModel\Adminhtml\Shipment\HsCodeFieldRenderer $hsCodeFieldRenderer */
$hsCodeFieldRenderer = $block->getCalcuratesHsCodeFieldRenderer();
$hsCodeFieldRenderer->setShipment($block->getShipment());
?>
<div class="grid">
    <?php $randomId = rand(); ?>
    <div class="admin__table-wrapper">
        <table id="packaging-data-grid-<?= /* @noEscape */ $randomId ?>" class="data-grid">
            <thead>
            <tr>
                <th class="data-grid-checkbox-cell">
                    <label class="data-grid-checkbox-cell-inner">
                        <input type="checkbox"
                               id="select-items-<?= /* @noEscape */ $randomId ?>"
                                <?php if (!isset($secureRenderer)): ?>
                                onchange="packaging.checkAllItems(this);"
                                <?php endif; ?>
                               class="checkbox admin__control-checkbox"
                               title="<?= $block->escapeHtmlAttr(__('Select All')) ?>">
                        <?php if (isset($secureRenderer)): ?>
                            <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                                'onchange',
                                'packaging.checkAllItems(this);',
                                'input#select-items-' . /* @noEscape */ $randomId
                            ) ?>
                        <?php endif; ?>
                        <label for="select-items-<?= /* @noEscape */ $randomId ?>"></label>
                    </label>
                </th>
                <th class="data-grid-th"><?= $block->escapeHtml(__('Product Name')) ?></th>
                <th class="data-grid-th"><?= $block->escapeHtml(__('Weight')) ?></th>
                <th class="data-grid-th custom-value"
                    <?php if (!$block->displayCustomsValue()): ?>
                        style="display: none;"
                    <?php endif; ?>
                >
                    <?= $block->escapeHtml(__('Customs Value')) ?>
                </th>
                <th class="data-grid-th hs-code-field"
                    <?php if (!$hsCodeFieldRenderer->isFieldRenderable()): ?>
                        style="display: none;"
                    <?php endif ?>
                ><?= $block->escapeHtml(__('HS Code')) ?></th>
                <th class="data-grid-th"><?= $block->escapeHtml(__('Qty Ordered')) ?></th>
                <th class="data-grid-th"><?= $block->escapeHtml(__('Qty')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php $i = 0; ?>
            <?php foreach ($block->getCollection() as $item): ?>
                <?php
                    $_order = $block->getShipment()->getOrder();
                    $_orderItem = $_order->getItemById($item->getOrderItemId());
                ?>
                <?php if ($item->getIsVirtual()
                    || ($_orderItem->isShipSeparately()
                        && !($_orderItem->getParentItemId() || $_orderItem->getParentItem()))
                    || (!$_orderItem->isShipSeparately()
                        && ($_orderItem->getParentItemId() || $_orderItem->getParentItem()))): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <tr class="data-grid-controls-row data-row <?= ($i++ % 2 != 0) ? '_odd-row' : '' ?>">
                    <td class="data-grid-checkbox-cell">
                        <?php $id = $item->getId() ?? $item->getOrderItemId(); ?>
                        <label class="data-grid-checkbox-cell-inner">
                            <input type="checkbox"
                                   name=""
                                   id="select-item-<?= /* @noEscape */ $randomId . '-' . $id ?>"
                                   value="<?= (int)$id ?>"
                                   class="checkbox admin__control-checkbox">
                            <label for="select-item-<?= /* @noEscape */ $randomId . '-' . $id ?>"></label>
                        </label>
                    </td>
                    <td>
                        <?= $block->escapeHtml($item->getName()) ?>
                    </td>
                    <td data-role="item-weight">
                        <?= $block->escapeHtml($item->getWeight()) ?>
                    </td>
                    <?php
                    if ($block->displayCustomsValue()) {
                        $customsValueValidation = ' validate-zero-or-greater ';
                    } else {
                        $customsValueValidation = '';
                    }

                    ?>
                    <td id="custom-value-<?= /* @noEscape */ $randomId . '-' . $id ?>" class="custom-value">
                        <input type="text"
                               name="customs_value"
                                <?php if (!$block->displayCustomsValue()): ?>
                                    style="display: none;"
                                <?php endif ?>
                               class="input-text admin__control-text <?= /* @noEscape */ $customsValueValidation ?>"
                               value="<?= $block->escapeHtmlAttr($block->formatPrice($item->getPrice())) ?>"
                               size="10">
                    </td>
                    <td id="hs-code-value-<?= /* @noEscape */ $randomId . '-' . $id ?>"
                        class="hs-code-value"
                        <?php if (!$hsCodeFieldRenderer->isFieldRenderable()): ?>
                            style="display: none;"
                        <?php endif ?>
                    >
                        <?= /** @noEscape  */$hsCodeFieldRenderer->render($item->getOrderItem()->getProduct()); ?>
                    </td>
                    <td>
                        <?= /* @noEscape */ $item->getOrderItem()->getQtyOrdered() * 1 ?>
                    </td>
                    <td>
                        <input type="hidden" name="price" value="<?= $block->escapeHtml($item->getPrice()) ?>">
                        <input type="text"
                               name="qty"
                               value="<?= /* @noEscape */ $item->getQty() * 1 ?>"
                               class="input-text admin__control-text qty
                            <?php if ($item->getOrderItem()->getIsQtyDecimal()): ?>
                               qty-decimal
                            <?php endif ?>">&nbsp;
                        <button type="button"
                                id="packaging-delete-item-<?= /* @noEscape */ $randomId . '-' . $id ?>"
                                style="display: none;"
                                class="action-delete"
                                data-action="package-delete-item">
                            <span><?= $block->escapeHtml(__('Delete')) ?></span>
                        </button>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
        <?php $scriptString = <<<script
        require(['jquery'], function ($) {
            $("#packaging-data-grid-{$randomId}").on('blur', 'td.custom-value input',
                function(){packaging.recalcContainerWeightAndCustomsValue(this)});
            $("#packaging-data-grid-{$randomId}").on('click', 'button[data-action="package-delete-item"]',
                function(){packaging.deleteItem(this)});
        });
script;
        ?>
        <?php if (isset($secureRenderer)): ?>
            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
        <?php else: ?>
            <script>
                <?= /** @noEscape  */ $scriptString ?>
            </script>
        <?php endif; ?>
    </div>
</div>
