<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2019-2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\Order\Packaging */ ?>
<?php /** @var $viewModel \Calcurates\ModuleMagento\ViewModel\ShippingLabel */ ?>
<?php
$shipmentId = (int)$block->getShipment()->getId();
$label = $viewModel->getLastShippingLabel($shipmentId);
$printUrl = $block->getUrl('adminhtml/order_shipment/printLabel', [
    'shipment_id' => $shipmentId
]);
if (!$label) {
    return;
}
?>
<div id="calcurates-shipping-label-data">
    <?= $block->getChildBlock('label_data_renderer')->render($label, $printUrl) ?>
</div>
<script>
    require([
        "jquery",
        "domReady!"
    ], function (jQuery) {
        var target = jQuery('#packed_window'),
            element = jQuery('#calcurates-shipping-label-data');

        target.append(element);
        element.show();
    });
</script>
