<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2019-2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\Order\Packaging */ ?>
<?php
/* @TODO: get label data from last label !*/
$labelData = $block->getShipment()->getData(\Calcurates\ModuleMagento\Api\Data\CustomSalesAttributesInterface::LABEL_DATA);
$printUrl = $block->getUrl('adminhtml/order_shipment/printLabel', [
    'shipment_id' => $block->getShipment()->getId()
]);
if (!$labelData) {
    return;
}
?>
<div id="calcurates-shipping-label-data">
    <?= $block->getChildBlock('label_data_renderer')->render($labelData, $printUrl) ?>
</div>
<script>
    require([
        "jquery",
        "domReady!"
    ], function (jQuery) {
        var target = jQuery('#packed_window'),
            element = jQuery('#calcurates-shipping-label-data');

        target.append(element);
        element.show();
    });
</script>
