<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2019-2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
?>
<?php /** @var $block \Magento\Shipping\Block\Adminhtml\Order\Packaging */ ?>
<?php
$sizeSource = $block->getSourceSizeModel()->toOptionArray(); // used in included `popup_content.phtml` file
$girthEnabled = $block->isDisplayGirthValue() && $block->isGirthAllowed(
) ? 1 : 0; // used in included `popup_content.phtml` file
/** @var \Calcurates\ModuleMagento\Helper\ShipmentAddressHelper $helper */
$helper = $this->helper(\Calcurates\ModuleMagento\Helper\ShipmentAddressHelper::class);
$shipment = $block->getShipment();
$order = $shipment->getOrder();
$isShipmentNew = !$shipment->getId();

/** @var \Calcurates\ModuleMagento\ViewModel\SmartPackaging $smartPackaging */
$smartPackaging = $block->getCalcuratesSmartPackaging();
$smartPackages = $smartPackaging->getPackages($shipment);
?>
<?php /** fix for magento 2.3.3 validation styles. Remove after fixing in magento */ ?>
<style type="text/css">
    .data-table input[type="text"].validation-failed {
        border-color: #e22626;
        box-shadow: 0 0 8px rgba(226, 38, 38, 0.6);
    }
</style>
<script>
    require([
        "jquery",
        "Calcurates_ModuleMagento/js/model/smart-packaging",
        "underscore",
        "mage/template",
        "prototype",
        "Magento_Shipping/order/packaging",
        "Magento_Ui/js/modal/modal"
    ], function (jQuery, smartPackaging, _, template) {
        var isShipmentNew = <?= $isShipmentNew ? 'true' : 'false' ?>,
            smartPackages = <?= $smartPackages ?>;
        window.packaging = new Packaging(<?= /* @noEscape */ $block->getConfigDataJson() ?>);
        packaging.changeContainerType($$('select[name=package_container]')[0]);
        packaging.checkSizeAndGirthParameter(
            $$('select[name=package_container]')[0],
            <?= /* @noEscape */ $girthEnabled ?>
        );
        packaging.setConfirmPackagingCallback(function () {
            packaging.setParamsCreateLabelRequest($('edit_form').serialize(true));
            packaging.sendCreateLabelRequest();
        });
        packaging.setLabelCreatedCallback(function (response) {
            setLocation("<?= $block->escapeJs(
                $block->escapeUrl(
                    $block->getUrl(
                        'sales/order/view',
                        ['order_id' => $block->getShipment()->getOrderId()]
                    )
                )
            ) ?>");
        });
        packaging.setCancelCallback(function () {
            var label = $('create_shipping_label');
            if (label.length) {
                packaging.cleanPackages();
                label.checked = false;
                toggleCreateLabelCheckbox();
            }
        });
        packaging.setItemQtyCallback(function (itemId) {
            var item = $$('[name="shipment[items][' + itemId + ']"]')[0],
                itemTitle = $('order_item_' + itemId + '_title');
            if (isShipmentNew && !itemTitle && !item) {
                return 0;
            }
            if (item && !isNaN(item.value)) {
                return item.value;
            }
        });

        Packaging.prototype.validate = function () {
            var dimensionElements = $('packaging_window').select(
                'input[name=container_length]:not([disabled]),input[name=container_width]:not([disabled]),input[name=container_height]:not([disabled]),input[name=container_girth]:not("._disabled")'
            );

            dimensionElements.each(function (element) {
                $(element).addClassName('required-entry');
            });

            return $$('[id^="package_block_"] input').collect(function (element) {
                return this.validateElement(element);
            }, this).all();
        };

        var packagingWindowOverviewButtons = [{
            text: '<?= $block->escapeJs($block->escapeHtml(__('Cancel'))) ?>',
            'class': 'action-secondary',
            click: function () {
                packaging.cancelPackaging();
                this.closeModal();
            }
        }, {
            text: '<?= $block->escapeJs($block->escapeHtml(__('Save'))) ?>',
            'attr': {'data-action': 'save-packages'},
            'class': 'action-primary',
            click: function () {
                packaging.setParamsCreateLabelRequest({
                    calcuratesShippingServiceId: jQuery('#calcurates_change_shipping_method_select').val()
                });
                packaging.confirmPackaging();
            }
        }, {
            text: '<?= $block->escapeJs($block->escapeHtml(__('Back To Packages'))) ?>',
            'attr': {'data-action': 'back-to-packages'},
            'class': 'action-secondary',
            click: function () {
                var $packagingWindow = jQuery('#packaging_window');
                $packagingWindow.modal('openModal');
                jQuery('#packaging_window_overview').modal('closeModal');
                packaging.messages = $packagingWindow.find('.message-warning').get(0);
            }
        }];

        var packagingWindowButtons = [{
            text: '<?= $block->escapeJs($block->escapeHtml(__('Cancel'))) ?>',
            'class': 'action-secondary',
            click: function () {
                packaging.cancelPackaging();
                this.closeModal();
            }
        }, {
            text: '<?= $block->escapeJs($block->escapeHtml(__('Next'))) ?>',
            'attr': {'disabled': 'disabled', 'data-action': 'save-packages'},
            'class': 'action-primary _disabled',
            click: function () {
                if (!packaging.validate()) {
                    packaging.messages.show().update(packaging.validationErrorMsg);

                    return;
                }
                packaging.messages.hide().update();

                var $packagingWindowOverview = jQuery('#packaging_window_overview');
                jQuery('#packaging_window').modal('closeModal');
                $packagingWindowOverview.modal('openModal');
                updatePackagesContentOverview();
                packaging.messages = $packagingWindowOverview.find('.message-warning').get(0);
            }
        }, {
            text: '<?= $block->escapeJs($block->escapeHtml(__('Add Package'))) ?>',
            'attr': {'data-action': 'add-packages'},
            'class': 'action-secondary',
            click: function () {
                packaging.newPackage();
            }
        }];

        jQuery('#packaging_window').modal({
            type: 'slide',
            title: '<?= $block->escapeJs($block->escapeHtml(__('Create Packages'))) ?>',
            buttons: packagingWindowButtons
        });
        jQuery(document).trigger('packaging:inited');
        jQuery(document).data('packagingInited', true);

        jQuery('#packaging_window_overview').modal({
            type: 'slide',
            title: '<?= $block->escapeJs($block->escapeHtml(__('Select Method and Confirm'))) ?>',
            buttons: packagingWindowOverviewButtons
        });

        jQuery('#calcurates_change_shipping_method').on('click', function () {
            jQuery('#calcurates_change_shipping_method_select').prop('disabled', false);
            return false;
        });

        function updatePackagesContentOverview() {
            var $packagesContent = jQuery('#packages_content_overview');

            $packagesContent.empty();
            jQuery.each(packaging.packagesContent.childElements(), function (i, pack) {
                var $pack = jQuery(pack);
                var weightUnitsSelect = $pack.find('select[name="container_weight_units"]').get(0);
                var dimensionUnitsSelect = $pack.find('select[name="container_dimension_units"]').get(0);
                var packageId = packaging.getPackageId(pack);

                var overviewHtml = template('#packages_content_overview_template', {
                    packageId: packageId,
                    weight: parseFloat($pack.find('input[name="container_weight"]').get(0).value || 0),
                    length: parseFloat($pack.find('input[name="container_length"]').get(0).value || 0),
                    width: parseFloat($pack.find('input[name="container_width"]').get(0).value || 0),
                    height: parseFloat($pack.find('input[name="container_height"]').get(0).value || 0),
                    weightUnits: weightUnitsSelect.options[weightUnitsSelect.selectedIndex].text,
                    dimensionUnits: dimensionUnitsSelect.options[dimensionUnitsSelect.selectedIndex].text
                });
                $packagesContent.append(overviewHtml);

                for (var packedItemId in packaging.packages[packageId]['items']) {
                    if (!isNaN(packedItemId)) {
                        var overviewItemsHtml = template('#packages_content_overview_items_template', {
                            productName: packaging.defaultItemsName[packedItemId],
                            productWeight: packaging.defaultItemsWeight[packedItemId],
                            productQty: packaging.packages[packageId]['items'][packedItemId]['qty']
                        });

                        $packagesContent.append(overviewItemsHtml);
                    }
                }

            });
        }

        if (!_.isEmpty(smartPackages)) {
            smartPackaging.init(window.packaging, smartPackages);
        }
    });
</script>
<?php
$block->assign(
    [
        'sizeSource' => $sizeSource,
        'girthEnabled' => $girthEnabled
    ]
);

echo /* @noEscape */
$block->fetchView($block->getTemplateFile('Calcurates_ModuleMagento::order/packaging/popup_content.phtml'));
?>
<div id="packaging_window_overview">
    <div class="message message-warning" style="display: none"></div>
    <div class="admin__page-section">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-payment-method">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= __('Shipping Method') ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <?php $shippingServiceId = $helper->getShippingServiceId($order, $shipment); ?>
                    <select name="calcurates_change_shipping_method_select"
                            id="calcurates_change_shipping_method_select"
                            class="select admin__control-select carrier required-entry"
                            <?php if ($shippingServiceId): ?>disabled="disabled"<?php endif; ?>>
                        <?php foreach ($helper->getShippingCarriersWithServices((int)$order->getStoreId()) as $shippingCarrier): ?>
                            <optgroup label="<?= $block->escapeHtml($shippingCarrier['label']) ?>">
                                <?php foreach ($shippingCarrier['options'] as $shippingService): ?>
                                    <option value="<?= $block->escapeHtml(
                                        $shippingService['value']
                                    ) ?>"<?= $shippingService['value'] == $shippingServiceId ? ' selected="selected"' : '' ?>>
                                        <?= $block->escapeHtml($shippingService['label']) ?>
                                    </option>
                                <?php endforeach; ?>
                            </optgroup>
                        <?php endforeach; ?>
                    </select>
                    <?php if ($shippingServiceId): ?>
                        <div class="actions" style="display: inline-block;margin-left: 0.5rem;">
                            <a href="#" id="calcurates_change_shipping_method">Edit</a>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>


    <section class="admin__page-section order-addresses">
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-billing-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= __('Origin Address') ?></span>
                    <span class="message message-notice notice hint">
                        <?= __('Make sure this address match Origin address that is specified in Calcurates as shipping label will be requested using the one from Calcurates.') ?>
                    </span>
                </div>
                <address class="admin__page-section-item-content">
                    <?= /* @noEscape */
                    $helper->getOriginAddressHtml($block->getShipment()) ?>
                </address>
            </div>
            <div class="admin__page-section-item order-shipping-address">
                <div class="admin__page-section-item-title">
                    <span class="title"><?= __('Shipping Address') ?></span>
                </div>
                <address class="admin__page-section-item-content"> <?= /* @noEscape */
                    $helper->getFormattedAddress($order->getShippingAddress()) ?></address>
            </div>
        </div>
    </section>

    <div id="packages_content_overview"></div>

    <script id="packages_content_overview_template" type="text/x-magento-template">
        <div class="admin__page-section-title">
            <span class="title">
                <?= __('Package') ?> <span data-role="package-number"><%- packageId %></span>
            </span>
        </div>
        <div style="margin-bottom: 10px;font-weight: 600;">
            <?= __('Custom Package') ?>, <%- weight %> <%- weightUnits %>
            <% if(length && width && height) { %>
                , <%- length %>x<%- width %>x<%- height %> <%- dimensionUnits %>
            <% } %>
        </div>
    </script>
    <script id="packages_content_overview_items_template" type="text/x-magento-template">
        <div class="admin__page-subsection package_items">
            <div class="grid">
                <div class="admin__table-wrapper">
                    <table class="data-grid">
                        <thead>
                        <tr>
                            <th class="data-grid-th"><?= __('Product Name') ?></th>
                            <th class="data-grid-th"><?= __('Weight') ?></th>
                            <th class="data-grid-th"><?= __('Qty') ?></th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="data-grid-controls-row data-row ">
                            <td><%- productName %></td>
                            <td data-role="item-weight"><%- productWeight %></td>
                            <td><%- productQty %></td>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </script>
</div>
