<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var $block \Magento\Sales\Block\Adminhtml\Order\Create\Shipping\Method\Form
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 * @var $escaper \Magento\Framework\Escaper
 * @var $orderDeliveryDates \Calcurates\ModuleMagento\ViewModel\OrderDeliveryDate
 * @var $quoteDeliveryDates \Calcurates\ModuleMagento\ViewModel\QuoteDeliveryDate
 */

use Calcurates\ModuleMagento\Client\RatesResponseProcessor;

?>
<?php
/** @var \Magento\Tax\Helper\Data $taxHelper */
$taxHelper = $block->getData('taxHelper');
$orderDeliveryDates = $block->getData('order_delivery_dates');
$quoteDeliveryDates = $block->getData('quote_delivery_dates');
?>
<?php $_shippingRateGroups = $block->getShippingRates(); ?>
<?php if ($_shippingRateGroups): ?>
    <div id="order-shipping-method-choose" class="control" style="display: none;">
        <dl class="admin__order-shipment-methods">
        <?php foreach ($_shippingRateGroups as $code => $_rates): ?>
            <dt class="admin__order-shipment-methods-title"><?= $block->escapeHtml($block->getCarrierName($code)) ?>
            </dt>
            <dd class="admin__order-shipment-methods-options">
                <ul class="admin__order-shipment-methods-options-list">
                <?php foreach ($_rates as $_rate): ?>
                    <?php $_radioProperty = 'name="order[shipping_method]" type="radio"' ?>
                    <?php $_code = $_rate->getCode() ?>
                    <li class="admin__field-option">
                        <?php if ($_rate->getErrorMessage()): ?>
                            <div class="messages">
                               <div class="message message-error error">
                                   <div><?= $block->escapeHtml($_rate->getErrorMessage()) ?></div>
                               </div>
                            </div>
                        <?php else: ?>
                            <?php $_checked = $block->isMethodActive($_code) ? 'checked="checked"' : '' ?>
                            <input <?= /* @noEscape */ $_radioProperty ?>
                                value="<?= $block->escapeHtmlAttr($_code) ?>"
                                <?php if (!isset($secureRenderer)): ?>
                                    onclick="order.setShippingMethod(this.value)"
                                <?php endif; ?>
                                id="s_method_<?= $block->escapeHtmlAttr($_code) ?>" <?= /* @noEscape */ $_checked ?>
                                class="admin__control-radio required-entry"/>
                            <label class="admin__field-label" for="s_method_<?= $block->escapeHtmlAttr($_code) ?>">
                                <?= $block->escapeHtml($_rate->getMethodTitle() ?
                                    $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?>
                                <?php if ($_code !== 'calcurates_metarate'): ?>
                                    <?= /* @noEscape */ $orderDeliveryDates->formatDeliveryDates(
                                        $quoteDeliveryDates->getDeliveryDates($_rate, $block->getQuote())
                                    ); ?>
                                &nbsp;-&nbsp;
                                <strong>
                                    <?php $_excl = $block->getShippingPrice(
                                        $_rate->getPrice(),
                                        $taxHelper->displayShippingPriceIncludingTax()
                                    ); ?>
                                    <?php $_incl = $block->getShippingPrice($_rate->getPrice(), true); ?>

                                    <?= /* @noEscape */ $_excl ?>
                                    <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?= $block->escapeHtml(__('Incl. Tax')) ?> <?= /* @noEscape */ $_incl ?>)
                                    <?php endif; ?>
                                </strong>
                                <?php endif; ?>
                            </label>
                            <?php if (isset($secureRenderer)): ?>
                                <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                                    'onclick',
                                    "order.setShippingMethod(this.value)",
                                    'input#s_method_' . $block->escapeHtmlAttr($_code)
                                ) ?>
                            <?php endif; ?>
                            <?php if ($_code === 'calcurates_metarate'): ?>
                                <?php $block->getChildBlock('metarate')
                                    ->setActiveMethod($block->getActiveMethodRate()) ?>
                                <?= $block->getChildHtml('metarate') ?>
                            <?php endif; ?>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            </dd>
        <?php endforeach; ?>
        </dl>
    </div>
    <?php $scriptString = <<<script
require(['prototype'], function(){
    $('order-shipping-method-choose').show();
});
script;
    ?>
    <?php if ($_rate = $block->getActiveMethodRate()): ?>
        <div id="order-shipping-method-info" class="order-shipping-method-info">
            <dl class="admin__order-shipment-methods">
                <dt class="admin__order-shipment-methods-title">
                    <?= $block->escapeHtml($block->getCarrierName($_rate->getCarrier())) ?>
                </dt>
                <dd class="admin__order-shipment-methods-options">
                    <?php if ($_rate->getCode() === 'calcurates_metarate'): ?>
                        <?= $block->escapeHtml($_rate->getMethodTitle() ?
                            $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?>
                    <?php else: ?>
                        <?= $block->escapeHtml($_rate->getMethodTitle() ?
                            $_rate->getMethodTitle() : $_rate->getMethodDescription()) ?>
                        <?= /* @noEscape */ $orderDeliveryDates->formatDeliveryDates(
                            $quoteDeliveryDates->getDeliveryDates($_rate, $block->getQuote())
                        ); ?>
                        &nbsp;-&nbsp;
                    <strong>
                        <?php $_excl = $block->getShippingPrice(
                            $_rate->getPrice(),
                            $taxHelper->displayShippingPriceIncludingTax()
                        ); ?>
                        <?php $_incl = $block->getShippingPrice($_rate->getPrice(), true); ?>

                        <?= /* @noEscape */ $_excl ?>
                        <?php if ($taxHelper->displayShippingBothPrices() && $_incl != $_excl): ?>
                            (<?= $block->escapeHtml(__('Incl. Tax')) ?> <?= /* @noEscape */ $_incl ?>)
                        <?php endif; ?>
                    </strong>
                    <?php endif; ?>
                </dd>
            </dl>
            <?php if ($_rate->getCode() === 'calcurates_metarate'): ?>
                <?php $block->getChildBlock('metarate')->setIsPreview(true) ?>
                <?= $block->getChildHtml('metarate', false) ?>
            <?php endif; ?>
            <a href="#"
                <?php if (!isset($secureRenderer)): ?>
               onclick="$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();return false"
                <?php endif; ?>
               class="action-default">
                <span><?= $block->escapeHtml(__('Click to change shipping method')) ?></span>
            </a>
        </div>
        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
            'onclick',
            "$('order-shipping-method-info').hide();$('order-shipping-method-choose').show();event.preventDefault()",
            'div#order-shipping-method-info a.action-default'
        ) ?>
    <?php else: ?>
        <?php if (isset($secureRenderer)): ?>
            <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
        <?php else: ?>
            <script>
                <?= /** @noEscape  */ $scriptString ?>
            </script>
        <?php endif; ?>
    <?php endif; ?>
<?php elseif ($block->getIsRateRequest()): ?>
    <div class="order-shipping-method-summary">
        <strong class="order-shipping-method-not-available">
            <?= $block->escapeHtml(__('Sorry, no quotes are available for this order.')) ?>
        </strong>
    </div>
<?php else: ?>
    <div id="order-shipping-method-summary" class="order-shipping-method-summary">
        <a href="#"
            <?php if (!isset($secureRenderer)): ?>
                onclick="order.loadShippingRates();event.preventDefault();"
            <?php endif; ?>
           class="action-default">
            <span><?= $block->escapeHtml(__('Get shipping methods and rates')) ?></span>
        </a>
        <input type="hidden" name="order[has_shipping]" value="" class="required-entry" />
    </div>
    <?php if (isset($secureRenderer)): ?>
        <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
            'onclick',
            "order.loadShippingRates();event.preventDefault();",
            'div#order-shipping-method-summary a.action-default'
        ) ?>
    <?php endif; ?>
<?php endif; ?>
<div id="shipping-method-overlay" class="order-methods-overlay" style="display: none;">
    <span><?= $block->escapeHtml(__('You don\'t need to select a shipping method.')) ?></span>
</div>
<?php $scriptString = <<<script
    require(["Magento_Sales/order/create/form"], function(){

script;
$scriptString .= "order.overlay('shipping-method-overlay', " . ($block->getQuote()->isVirtual() ? 'false' : 'true') .
    ');' . PHP_EOL;
$scriptString .= "order.overlay('address-shipping-overlay', " . ($block->getQuote()->isVirtual() ? 'false' : 'true') .
 ');' . PHP_EOL;
$scriptString .= "order.isOnlyVirtualProduct = " . ($block->getQuote()->isVirtual() ? 'true' : 'false') . ';' . PHP_EOL;
$scriptString .= <<<script
    });
script;
?>
<?php if (isset($secureRenderer)): ?>
    <?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false) ?>
<?php else: ?>
    <script>
        <?= /** @noEscape  */ $scriptString ?>
    </script>
<?php endif; ?>
