<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\Adminhtml\MetaRate
 * @var $secureRenderer \Magento\Framework\View\Helper\SecureHtmlRenderer
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$viewModel = $block->getViewModel();
$origins = $viewModel->getMetaRateData()->getOriginData();
$rates = $viewModel->getMetaRateData()->getRatesData();
$productData = $viewModel->getMetaRateData()->getProductData();
$productStockData = $viewModel->getMetaRateData()->getProductQtys();
$shipmentCount = 1;
$isSelected = $block->getActiveMethod() && $block->getActiveMethod()->getCode() === 'calcurates_metarate';
?>
<div class="metarates-wrapper"
<?php if (!$isSelected): ?>
     style="display: none;"
<?php endif; ?>
>
<?php foreach ($origins ?? [] as $origin): ?>
    <b><?= $block->escapeHtml(__('Shipment %1 of %2', $shipmentCount++, count($origins))) ?></b><br>
    <?php
    $itemIds = $productStockData
        ? $viewModel->getProductSkuQty($productStockData[$origin['id']] ?? [])
        : $viewModel->getSkusListByItemIds($productData[$origin['id']] ?? [])
    ?>
    <span><?= $block->escapeHtml(__('Included SKUs: %1', implode(', ', $itemIds))) ?></span><br>
    <?php if (!$block->getIsPreview()): ?>
    <select name="origin[<?= /** @noEscape  */ $origin['id'] ?>]"
            id="origin-<?= /** @noEscape  */ $origin['id'] ?>"
            <?php if (!isset($secureRenderer)): ?>
            onchange="order.setShippingMethod('calcurates_metarate')"
            <?php endif; ?>
            class="select admin__control-select <?= $isSelected ? '' : 'ignore-validate' ?>"
            data-validate="{'validate-select': true}"
            data-origin="<?= /** @noEscape  */ $origin['id'] ?>">
        <option value="">
            <?= $block->escapeHtml(__('Please select a shipping method...')); ?>
        </option>
        <?php foreach ($rates[$origin['id']] as $rate): ?>
            <option value="<?= /** @noEscape  */ $rate->getMethod() ?>"
                <?= $viewModel->isSavedMethod($origin['id'], $rate->getMethod()) ? ' selected="selected"' : ''; ?>
            >
                <?= /** @noEscape  */ $viewModel->renderShippingRateOption($rate) ?>
            </option>
        <?php endforeach; ?>
    </select><br>
        <?php if (isset($secureRenderer)): ?>
            <?= /* @noEscape */ $secureRenderer->renderEventListenerAsTag(
                'onchange',
                "order.setShippingMethod('calcurates_metarate')",
                'select#origin-' . $origin['id']
            ) ?>
        <?php endif; ?>
    <?php else: ?>
        <span><?= $block->escapeHtml(__('Method:'))?></span>
        <?php foreach ($rates[$origin['id']] as $rate): ?>
            <?php if ($viewModel->isSavedMethod($origin['id'], $rate->getMethod())): ?>
                <span><?= /** @noEscape  */ $viewModel->renderShippingRateOption($rate) ?></span><br>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
<?php endforeach; ?>
</div>
