<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */
?>
<?php
/**
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\OrderShippingAdditionalInfo
 * @var \Magento\Framework\View\Element\Template $block
 */
?>
<?php $_shipment = $block->getShipment() ?>
<?php
/* @var \Magento\Sales\Model\Order $_order */
$_order = $block->getOrder();
?>
<?php if ($_shipment && $_order) : ?>
    <?php $viewModel = $block->getViewModel(); ?>
    <?php $viewModel->setOrder($_order); ?>
    <?php $trackCollection = $_order->getTracksCollection($_shipment->getId()) ?>
    <?php if ($trackCollection) : ?>
        <br />
        <table class="shipment-track">
            <thead>
            <tr>
                <th><?= $block->escapeHtml(__('Shipped By')) ?></th>
                <th><?= $block->escapeHtml(__('Tracking Number')) ?></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($trackCollection as $_item) : ?>
                <tr>
                    <td><?= $block->escapeHtml($_item->getTitle()) ?>:</td>
                    <td>
                        <?php if ($viewModel->isTrackable($_item->getShipment())): ?>
                            <a href="<?= $block->escapeUrl($block->getTrackingUrl()->getUrl($_item)) ?>" target="_blank">
                                <?= $block->escapeHtml($_item->getNumber()) ?>
                            </a>
                        <?php else: ?>
                            <?= $block->escapeHtml($_item->getNumber()) ?>
                        <?php endif; ?>
                    </td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table>
    <?php endif; ?>
<?php endif; ?>
