<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\MetaRate
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$viewModel = $block->getViewModel();
$origins = $viewModel->getMetaRateData()->getOriginData();
$rates = $viewModel->getMetaRateData()->getRatesData();
$productData = $viewModel->getMetaRateData()->getProductData();
$productStockData = $viewModel->getMetaRateData()->getProductQtys();
$shipmentCount = 1;
?>
<div class="metarates-wrapper" style="display: none;">
<?php foreach ($origins ?? [] as $origin): ?>
    <b><?= $block->escapeHtml(__('Shipment %1 of %2', $shipmentCount++, count($origins))) ?></b><br>
    <?php
    $itemIds = $productStockData
        ? $viewModel->getProductSkuQty($productStockData[$origin['id']] ?? [])
        : $viewModel->getSkusListByItemIds($productData[$origin['id']] ?? [])
    ?>
    <?php $itemIds = $viewModel->getSkusListByItemIds($productData[$origin['id']] ?? []) ?>
    <span><?= $block->escapeHtml(__('Included SKUs: %1', implode(', ', $itemIds))) ?></span>
    <select name="origin[<?= /* @noEscape */ $origin['id'] ?>]"
            id="origin-<?= /* @noEscape */ $origin['id'] ?>"
            class="select">
        <option value="">
            <?= $block->escapeHtml(__('Please select a shipping method...')); ?>
        </option>
        <?php foreach ($rates[$origin['id']] as $rate): ?>
            <?php if ($rate->getErrorMessage()): ?>
                <option value="<?= /** @noEscape  */ $viewModel->getErrorRateOptionValue($rate) ?>" disabled>
                    <?= /** @noEscape  */ $viewModel->renderShippingRateErrorOption($rate) ?>
                </option>
            <?php else: ?>
                <option value="<?= /** @noEscape  */ $rate->getMethod() ?>"
                    <?= $viewModel->isSavedMethod($origin['id'], $rate->getMethod()) ? ' selected="selected"' : ''; ?>
                >
                    <?= /** @noEscape  */ $viewModel->renderShippingRateOption($rate) ?>
                </option>
            <?php endif; ?>
        <?php endforeach; ?>
    </select>
<?php endforeach; ?>
</div>
