<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var $block \Magento\Framework\View\Element\Template
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\MetaRate
 */
?>
<?php
    $viewModel = $block->getViewModel();
    $origins = $viewModel->getMetaRateData()->getOriginData();
    $rates = $viewModel->getMetaRateData()->getRatesData();
    $shipNumber = 1;
    $shipSize = count($origins);
?>
<div class="metarate">
    <?php foreach ($origins as $origin): ?>
        <span>Shipping <?= $shipNumber++ ?> of <?= $shipSize ?></span>
        <select name="origin[<?= $origin['id'] ?>]" id="origin-<?= $origin['id'] ?>" class="select">
            <option value="">
                <?= $block->escapeHtml(__('Please select a shipping method...')); ?>
            </option>
            <?php foreach ($rates[$origin['id']] as $rate): ?>
                <option value="<?= $rate->getMethod() ?>"><?= $rate->getMethodTitle() ?></option>
            <?php endforeach; ?>
        </select>
    <?php endforeach; ?>

</div>
