<?php
/**
 * @author Calcurates Team
 * @copyright Copyright © 2020 Calcurates (https://www.calcurates.com)
 * @license https://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 * @package Calcurates_ModuleMagento
 */

/**
 * @var $block \Calcurates\ModuleMagento\Block\Paypal\Express\Review\Metarate
 * @var $viewModel \Calcurates\ModuleMagento\ViewModel\MetaRate
 * @var $escaper \Magento\Framework\Escaper
 */
?>
<?php
$viewModel = $block->getViewModel();
$origins = $viewModel->getMetaRateData()->getOriginData();
$rates = $viewModel->getMetaRateData()->getRatesData();
$productData = $viewModel->getMetaRateData()->getProductData();
$shipmentCount = 1;
?>
<div class="metarates-wrapper" style="display: none;">
<?php foreach ($origins ?? [] as $origin): ?>
    <b><?= $escaper->escapeHtml(__('Shipment %1 of %2', $shipmentCount++, count($origins))) ?></b><br>
    <?php $itemIds = $viewModel->getSkusListByItemIds($productData[$origin['id']] ?? []) ?>
    <span><?= $escaper->escapeHtml(__('Included SKUs: %1', implode(', ', $itemIds))) ?></span>
    <select name="origin[<?= $origin['id'] ?>]" id="origin-<?= $origin['id'] ?>" class="select">
        <option value="">
            <?= $escaper->escapeHtml(__('Please select a shipping method...')); ?>
        </option>
        <?php foreach ($rates[$origin['id']] as $rate): ?>
            <option value="<?= $rate->getMethod() ?>"
                <?= $viewModel->isSavedMethod($origin['id'], $rate->getMethod()) ? ' selected="selected"' : ''; ?>
            >
                <?= $viewModel->renderShippingRateOption($rate) ?>
            </option>
        <?php endforeach; ?>
    </select>
<?php endforeach; ?>
</div>
